In [25]:
import numpy as np
import pandas as pd
import sklearn

In [26]:
data = pd.read_csv(r'C:\Users\91994\Desktop\git\New folder\dataset\Admission_Predict.csv')
 


In [27]:
data.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [28]:
data = pd.get_dummies(data,columns=['Research'])

In [29]:
data.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Chance of Admit   Research_0  Research_1  
0              0.92           0           1  
1              0.76           0           1  
2              0.72           0           1  
3              0.80           0           1  
4              0.65           1           0

In [30]:
x=data.drop('Research_1',axis=1)

In [31]:
y=data['Research_1']

In [32]:
x

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

     Chance of Admit   Research_0  
0                0.92           0  
1                0.76           0  
2                0.72           0  
3                0.80           0  
4                0.65           1  
..                ...         ...  
395              0.82           0  
396              0.84           0  
397              0.91           0  
398              0.67           1  
399              0.95           0  

[400 rows x 9 columns]

In [33]:
y

0      1
1      1
2      1
3      1
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Research_1, Length: 400, dtype: uint8

In [34]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
x_scaled = mm.fit_transform(x)

In [35]:
x_scaled

array([[0.        , 0.94      , 0.92857143, ..., 0.91346154, 0.92063492,
        0.        ],
       [0.00250627, 0.68      , 0.53571429, ..., 0.66346154, 0.66666667,
        0.        ],
       [0.00501253, 0.52      , 0.42857143, ..., 0.38461538, 0.6031746 ,
        0.        ],
       ...,
       [0.99498747, 0.8       , 0.85714286, ..., 0.84935897, 0.9047619 ,
        0.        ],
       [0.99749373, 0.44      , 0.39285714, ..., 0.63461538, 0.52380952,
        1.        ],
       [1.        , 0.86      , 0.89285714, ..., 0.91666667, 0.96825397,
        0.        ]])

In [36]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_scaled,y,test_size=0.4,random_state=1)

In [37]:
from sklearn.linear_model import LogisticRegression
lor = LogisticRegression()
lor.fit(x_train,y_train)

LogisticRegression()

In [38]:
pred_test = lor.predict(x_test)

In [39]:
pred_test

array([0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0], dtype=uint8)

In [40]:
y_test

398    0
125    1
328    1
339    1
172    1
      ..
340    1
70     1
38     0
150    1
208    0
Name: Research_1, Length: 160, dtype: uint8

Evaluation Metrics

#Accuracy Score

In [41]:
from sklearn.metrics import accuracy_score
accuracy_score(pred_test,y_test)

1.0

In [42]:
from sklearn.metrics import confusion_matrix

In [43]:
confusion_matrix(pred_test,y_test)

array([[70,  0],
       [ 0, 90]], dtype=int64)

In [44]:
y_test.shape

(160,)

In [45]:
y_test.value_counts()

1    90
0    70
Name: Research_1, dtype: int64

In [46]:
confusion_matrix(pred_test,y_test)

array([[70,  0],
       [ 0, 90]], dtype=int64)

In [47]:
from sklearn.metrics import classification_report


In [48]:
print(classification_report(pred_test, y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        70
           1       1.00      1.00      1.00        90

    accuracy                           1.00       160
   macro avg       1.00      1.00      1.00       160
weighted avg       1.00      1.00      1.00       160

